name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint files
        uses: PaulienM/xmllint-action@v1.1
        with:
          test-file: ./test.sh
